---
- name: Install Ansible DConf Module Dependency
  become: yes
  package:
    name: python3-psutil
    state: present

- name: Install RPM Fusion Repository
  become: yes
  command: /usr/bin/dnf install -y "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm" "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"

- name: Install Media Codecs
  become: yes
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - gstreamer1-libav 
    - gstreamer1-plugins-bad-free-extras 
    - gstreamer1-plugins-bad-freeworld 
    - gstreamer1-plugins-base-tools 
    - gstreamer1-plugins-good-extras 
    - gstreamer1-plugins-ugly 
    - gstreamer1-plugins-bad-free 
    - gstreamer1-plugins-good 
    - gstreamer1-plugins-base 
    - gstreamer1
    - ffmpeg
    - compat-ffmpeg28 
    - ffmpeg-libs
    - libmatroska
    - chromium-libs-media-freeworld

- name: Install SeaHorse to encrypt and decrypt files easily
  become: yes
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - seahorse
    - seahorse-nautilus

- name: Install Other Tools
  become: yes
  package:
    name: "{{ packages }}"
  vars:
    packages:
    - neovim
    - htop
    - gnome-tweaks