---
# Install ZSH
# dnf install -y zsh
# sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
# sudo usermod -s /usr/bin/zsh yourlogin
# add to path (zshrc)
# $HOME/.local/bin

- name: Install ZSH
  become: yes
  package:
    name: zsh
    state: present

- name: Download Oh-My-Zsh
  get_url:
    url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
    dest: /tmp/
    mode: 0740

- name: Install Oh-My-Zsh
  command: sh -c "/tmp/install.sh"
  environment:
        ZSH: "{{ansible_env.HOME}}/.local/share/oh-my-zsh"
  register: omzsh_install
  changed_when: omzsh_install.rc == 0
  failed_when: 
    - omzsh_install.rc != 0
    - omzsh_install.rc != 1

- name: Change Zsh Theme
  lineinfile: 
    dest: ~/.zshrc 
    regexp: "^ZSH_THEME=(.*)" 
    line: 'ZSH_THEME="gianu"' 
    state: present 
    backup: yes 
    backrefs: yes

# On dotfiles
# - name: Add Open Alias to Zsh config
#   lineinfile: 
#     dest: ~/.zshrc 
#     line: 'alias open="xdg-open"' 
#     state: present 
#     backup: yes 
#
# - name: Add dnf cache Alias to Zsh config
#   lineinfile: 
#     dest: ~/.zshrc 
#     line: 'alias dnf="dnf --cacheonly --color=auto"' 
#     state: present 
#     backup: yes
#
# - name: Set PATH on Zsh config
#   lineinfile: 
#     dest: ~/.zshrc 
#     regexp: "export PATH=(.*)" 
#     line: 'export PATH=$HOME/.local/bin:$PATH' 
#     state: present 
#     backup: yes 
#     backrefs: yes

- name: Change user's shell
  become: yes
  command: usermod --shell /usr/bin/zsh {{ ansible_user_id }}
  register: userm
  changed_when: '"no changes" in userm.stdout'