- name: Enable GTK4 Dark Theme
  dconf:
    key: /org/gnome/desktop/interface/color-scheme
    value: "'prefer-dark'"

- name: Enable Dark Theme for Legacy applications
  dconf:
    key: /org/gnome/desktop/interface/gtk-theme
    value: "'Adwaita-dark'"

- name: Set Locale Region
  dconf:
    key: /system/locale/region
    value: "'en_GB.UTF-8'"

- name: Show Date on Clock
  dconf:
    key: /org/gnome/desktop/interface/clock-show-date
    value: "true"

- name: Show Battery Percentage
  dconf:
    key: /org/gnome/desktop/interface/show-battery-percentage
    value: "true"

- name: Show Weekdate
  dconf:
    key: /org/gnome/desktop/calendar/show-weekdate
    value: "true"

- name: Change WM Button Layout
  dconf:
    key: /org/gnome/desktop/wm/preferences/button-layout
    value: "'appmenu:minimize,maximize,close'"

- name: Enable Night Light
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
    value: "true"

- name: Set Night Light Temperature
  dconf:
    key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
    value: "uint32 5500"

- name: Remove from search
  dconf:
    key: /org/gnome/desktop/search-providers/disabled
    value: "['org.gnome.Contacts.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Characters.desktop', 'org.gnome.clocks.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Software.desktop']"

- name: Add Downloads to search index folders
  dconf:
    key: /org/freedesktop/tracker/miner/files/index-recursive-directories
    value: "['&DESKTOP', '&DOCUMENTS', '&MUSIC', '&PICTURES', '&VIDEOS', '&DOWNLOAD']"

- name: Multitasking - Disable hot corners
  dconf:
    key: /org/gnome/desktop/interface/enable-hot-corners
    value: "false"