# Privacy settings
- name: Disable location services
  dconf:
    key: /org/gnome/system/location/enabled
    value: "false"

# Screen Lock
- name: Enable screen lock
  dconf:
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: "true"

- name: Screen lock delay after blank screen (seconds)
  dconf:
    key: /org/gnome/desktop/screensaver/lock-delay
    value: "uint32 0"

- name: Screen blank screen delay (seconds)
  dconf:
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 120"
