# Privacy settings
- name: Disable location services
  dconf:
    key: /org/gnome/system/location/enabled
    value: "false"

# Screen Lock
- name: Enable screen lock
  dconf:
    key: /org/gnome/desktop/screensaver/lock-enabled
    value: "true"

- name: Screen lock delay after blank screen (seconds)
  dconf:
    key: /org/gnome/desktop/screensaver/lock-delay
    value: "uint32 0"

- name: Screen blank screen delay (seconds)
  dconf:
    key: /org/gnome/desktop/session/idle-delay
    value: "uint32 120"

- name: Remove from search
  dconf:
    key: /org/gnome/desktop/search-providers/disabled
    value: "['org.gnome.Contacts.desktop', 'org.gnome.Calendar.desktop', 'org.gnome.Characters.desktop', 'org.gnome.clocks.desktop', 'org.gnome.Terminal.desktop', 'org.gnome.Software.desktop']"
