- name: Create Projects directory
  file:
    path: ~/Projects
    state: directory

- name: Clone Public Personal Repositories
  git:
    dest: "~/Projects/lucasqlm/{{ item }}"
    repo: "https://github.com/lucasqlm/{{ item }}.git"
  loop:
    - python-webapp
    - linux-post-install

- name: Clone Distrobox Repository
  git:
    dest: "~/Projects/git/distrobox"
    repo: https://github.com/89luca89/distrobox.git

- name: Install Distrobox
  command: ~/Projects/git/distrobox/install --prefix ~/.local
